<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VendasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('venda')->insert([
            [
                'id' => 1,
                'descricao' => 'Venda em 10 parcelas',
                'preco_venda' => 16000,
                'data_venda' => '2023-11-01',
                'funcionario_id' => 1,
                'loja_id' => 1,
                'moto_id' => 1,
                'metodo_pagamento_id' => 1,
                'created_at' => '2023-11-01 08:00:00',
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'descricao' => 'Compra de teste',
                'preco_venda' => 19000,
                'data_venda' => '2023-10-02',
                'funcionario_id' => 1,
                'loja_id' => 1,
                'moto_id' => 2,
                'metodo_pagamento_id' => 1,
                'created_at' => '2023-10-02 14:30:00',
                'updated_at' => '2023-10-02 14:30:00',
            ],
            [
                'id' => 3,
                'descricao' => 'Compra de teste',
                'preco_venda' => 18000,
                'data_venda' => '2023-09-03',
                'funcionario_id' => 1,
                'loja_id' => 2,
                'moto_id' => 2,
                'metodo_pagamento_id' => 1,
                'created_at' => '2023-09-03 10:15:00',
                'updated_at' => '2023-09-03 10:15:00',
            ],
            [
                'id' => 4,
                'descricao' => 'Venda especial',
                'preco_venda' => 19000,
                'data_venda' => '2023-12-04',
                'funcionario_id' => 1,
                'loja_id' => 1,
                'moto_id' => 3,
                'metodo_pagamento_id' => 2,
                'created_at' => '2023-12-04 16:45:00',
                'updated_at' => '2023-12-04 16:45:00',
            ],
            [
                'id' => 5,
                'descricao' => 'Moto econômica',
                'preco_venda' => 18000,
                'data_venda' => '2023-12-05',
                'funcionario_id' => 1,
                'loja_id' => 1,
                'moto_id' => 3,
                'metodo_pagamento_id' => 1,
                'created_at' => '2023-12-05 09:20:00',
                'updated_at' => '2023-12-05 09:20:00',
            ],
            [
                'id' => 6,
                'descricao' => 'Compra de teste',
                'preco_venda' => 18000,
                'data_venda' => '2023-10-06',
                'funcionario_id' => 1,
                'loja_id' => 3,
                'moto_id' => 2,
                'metodo_pagamento_id' => 1,
                'created_at' => '2023-10-06 15:10:00',
                'updated_at' => '2023-10-06 15:10:00',
            ],
            [
                'id' => 7,
                'descricao' => 'Compra divertida',
                'preco_venda' => 18000,
                'data_venda' => '2023-09-07',
                'funcionario_id' => 1,
                'loja_id' => 3,
                'moto_id' => 3,
                'metodo_pagamento_id' => 1,
                'created_at' => '2023-09-07 11:05:00',
                'updated_at' => '2023-09-07 11:05:00',
            ],
            [
                'id' => 8,
                'descricao' => 'Teste de compra',
                'preco_venda' => 17000,
                'data_venda' => '2023-11-08',
                'funcionario_id' => 1,
                'loja_id' => 5,
                'moto_id' => 4,
                'metodo_pagamento_id' => 2,
                'created_at' => '2023-11-08 12:30:00',
                'updated_at' => '2023-11-08 12:30:00',
            ],
            [
                'id' => 9,
                'descricao' => 'Compra OK',
                'preco_venda' => 18500,
                'data_venda' => '2023-09-09',
                'funcionario_id' => 1,
                'loja_id' => 4,
                'moto_id' => 3,
                'metodo_pagamento_id' => 1,
                'created_at' => '2023-09-09 17:50:00',
                'updated_at' => '2023-09-09 17:50:00',
            ],
            [
                'id' => 10,
                'descricao' => 'Teste de compra com valor elevado',
                'preco_venda' => 18000,
                'data_venda' => '2023-12-10',
                'funcionario_id' => 1,
                'loja_id' => 5,
                'moto_id' => 2,
                'metodo_pagamento_id' => 2,
                'created_at' => '2023-12-10 14:15:00',
                'updated_at' => '2023-12-10 14:15:00',
            ],
            [
                'id' => 11,
                'descricao' => 'Descrição da compra',
                'preco_venda' => 17000,
                'data_venda' => '2023-11-11',
                'funcionario_id' => 1,
                'loja_id' => 4,
                'moto_id' => 5,
                'metodo_pagamento_id' => 1,
                'created_at' => '2023-11-11 18:30:00',
                'updated_at' => '2023-11-11 18:30:00',
            ],
            [
                'id' => 12,
                'descricao' => 'Compra de teste',
                'preco_venda' => 19000,
                'data_venda' => '2023-11-02',
                'funcionario_id' => 1,
                'loja_id' => 1,
                'moto_id' => 2,
                'metodo_pagamento_id' => 1,
                'created_at' => '2023-11-02 14:30:00',
                'updated_at' => '2023-11-02 14:30:00',
            ],
            [
                'id' => 13,
                'descricao' => 'Compra de teste',
                'preco_venda' => 18000,
                'data_venda' => '2023-11-03',
                'funcionario_id' => 1,
                'loja_id' => 2,
                'moto_id' => 2,
                'metodo_pagamento_id' => 1,
                'created_at' => '2023-11-03 10:15:00',
                'updated_at' => '2023-11-03 10:15:00',
            ],
            [
                'id' => 14,
                'descricao' => 'Venda especial',
                'preco_venda' => 19000,
                'data_venda' => '2023-11-04',
                'funcionario_id' => 1,
                'loja_id' => 1,
                'moto_id' => 3,
                'metodo_pagamento_id' => 2,
                'created_at' => '2023-11-04 16:45:00',
                'updated_at' => '2023-11-04 16:45:00',
            ],
            [
                'id' => 15,
                'descricao' => 'Moto econômica',
                'preco_venda' => 18000,
                'data_venda' => '2023-11-05',
                'funcionario_id' => 1,
                'loja_id' => 1,
                'moto_id' => 3,
                'metodo_pagamento_id' => 1,
                'created_at' => '2023-11-05 09:20:00',
                'updated_at' => '2023-11-05 09:20:00',
            ],
        ]);
    }
}